"""submission media review and drive commit models

Revision ID: 3ce7591b41e6
Revises: a7319c6502b1
Create Date: 2026-09-08 06:00:40.253786

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3ce7591b41e6"
down_revision = "a7319c6502b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "queue_allocations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_folder", sa.String(length=200), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("last_number", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "platform IN ('instagram','facebook','linkedin','youtube')",
            name=op.f("ck_queue_allocations_valid_queue_platform"),
        ),
        sa.CheckConstraint(
            "last_number >= 0", name=op.f("ck_queue_allocations_nonnegative_queue_number")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_queue_allocations")),
        sa.UniqueConstraint(
            "campaign_folder", "target_date", "platform", name="queue_allocation_unique"
        ),
    )
    op.create_table(
        "submissions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.String(length=100), nullable=False),
        sa.Column("campaign_name_snapshot", sa.String(length=200), nullable=False),
        sa.Column("campaign_folder_snapshot", sa.String(length=200), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column("default_caption", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("reviewed_by_id", sa.Integer(), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT','PENDING_APPROVAL','CHANGES_REQUESTED','APPROVING','APPROVED','DRIVE_ERROR','REJECTED')",
            name=op.f("ck_submissions_valid_submission_status"),
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["users.id"], name=op.f("fk_submissions_creator_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"], ["users.id"], name=op.f("fk_submissions_reviewed_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submissions")),
    )
    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_submissions_campaign_id"), ["campaign_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_submissions_creator_id"), ["creator_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_submissions_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_submissions_target_date"), ["target_date"], unique=False
        )

    op.create_table(
        "submission_platforms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("detected_post_type", sa.String(length=20), nullable=True),
        sa.Column("selected_post_type", sa.String(length=20), nullable=True),
        sa.Column("placement", sa.String(length=20), nullable=False),
        sa.Column("caption_override", sa.Text(), nullable=True),
        sa.Column("compatibility_message", sa.String(length=500), nullable=True),
        sa.Column("is_compatible", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("reviewed_by_id", sa.Integer(), nullable=True),
        sa.Column("drive_post_folder_id", sa.String(length=200), nullable=True),
        sa.Column("drive_post_folder_name", sa.String(length=20), nullable=True),
        sa.Column("drive_post_json_file_id", sa.String(length=200), nullable=True),
        sa.Column("committed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "detected_post_type IS NULL OR detected_post_type IN ('text','image','video','carousel','story','document')",
            name=op.f("ck_submission_platforms_valid_detected_type"),
        ),
        sa.CheckConstraint(
            "placement IN ('standard','story')",
            name=op.f("ck_submission_platforms_valid_placement"),
        ),
        sa.CheckConstraint(
            "platform IN ('instagram','facebook','linkedin','youtube')",
            name=op.f("ck_submission_platforms_valid_platform"),
        ),
        sa.CheckConstraint(
            "selected_post_type IS NULL OR selected_post_type IN ('text','image','video','carousel','story','document')",
            name=op.f("ck_submission_platforms_valid_selected_type"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','PENDING_APPROVAL','CHANGES_REQUESTED','APPROVING','APPROVED','DRIVE_ERROR','REJECTED')",
            name=op.f("ck_submission_platforms_valid_variant_status"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["users.id"],
            name=op.f("fk_submission_platforms_reviewed_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_submission_platforms_submission_id_submissions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submission_platforms")),
        sa.UniqueConstraint("submission_id", "platform", name="submission_platform_unique"),
    )
    with op.batch_alter_table("submission_platforms", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_submission_platforms_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_submission_platforms_submission_id"), ["submission_id"], unique=False
        )

    op.create_table(
        "drive_commit_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("submission_platform_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("post_number", sa.Integer(), nullable=True),
        sa.Column("post_folder_name", sa.String(length=20), nullable=True),
        sa.Column("drive_campaign_folder_id", sa.String(length=200), nullable=True),
        sa.Column("drive_date_folder_id", sa.String(length=200), nullable=True),
        sa.Column("drive_platform_folder_id", sa.String(length=200), nullable=True),
        sa.Column("drive_post_folder_id", sa.String(length=200), nullable=True),
        sa.Column("drive_media_folder_id", sa.String(length=200), nullable=True),
        sa.Column("drive_caption_file_id", sa.String(length=200), nullable=True),
        sa.Column("drive_post_json_file_id", sa.String(length=200), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('QUEUED','RUNNING','COMPLETED','FAILED','UNCERTAIN')",
            name=op.f("ck_drive_commit_attempts_valid_commit_status"),
        ),
        sa.ForeignKeyConstraint(
            ["submission_platform_id"],
            ["submission_platforms.id"],
            name=op.f("fk_drive_commit_attempts_submission_platform_id_submission_platforms"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drive_commit_attempts")),
    )
    with op.batch_alter_table("drive_commit_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_drive_commit_attempts_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_drive_commit_attempts_submission_platform_id"),
            ["submission_platform_id"],
            unique=False,
        )

    op.create_table(
        "media_assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("submission_platform_id", sa.Integer(), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("staged_name", sa.String(length=80), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("sort_order >= 1", name=op.f("ck_media_assets_positive_media_order")),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_media_assets_submission_id_submissions"),
        ),
        sa.ForeignKeyConstraint(
            ["submission_platform_id"],
            ["submission_platforms.id"],
            name=op.f("fk_media_assets_submission_platform_id_submission_platforms"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
        sa.UniqueConstraint("staged_name", name="media_staged_name_unique"),
    )
    with op.batch_alter_table("media_assets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_media_assets_submission_id"), ["submission_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_media_assets_submission_platform_id"),
            ["submission_platform_id"],
            unique=False,
        )

    op.create_table(
        "review_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("submission_platform_id", sa.Integer(), nullable=True),
        sa.Column("actor_id", sa.Integer(), nullable=False),
        sa.Column("actor_name", sa.String(length=120), nullable=False),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "action IN ('SUBMITTED','CHANGES_REQUESTED','REJECTED','APPROVED')",
            name=op.f("ck_review_events_valid_review_action"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_review_events_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_review_events_submission_id_submissions"),
        ),
        sa.ForeignKeyConstraint(
            ["submission_platform_id"],
            ["submission_platforms.id"],
            name=op.f("fk_review_events_submission_platform_id_submission_platforms"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_events")),
    )
    with op.batch_alter_table("review_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_review_events_submission_id"), ["submission_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_review_events_submission_platform_id"),
            ["submission_platform_id"],
            unique=False,
        )

    if op.get_bind().dialect.name == "postgresql":
        op.execute("""CREATE TRIGGER review_events_no_changes BEFORE UPDATE OR DELETE ON review_events
                      FOR EACH ROW EXECUTE FUNCTION prevent_audit_mutation()""")
        op.execute("""CREATE TRIGGER review_events_no_truncate BEFORE TRUNCATE ON review_events
                      FOR EACH STATEMENT EXECUTE FUNCTION prevent_audit_mutation()""")
        op.execute("""
            DO $$ BEGIN
              IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'social_app') THEN
                GRANT SELECT, INSERT, UPDATE, DELETE ON submissions, submission_platforms,
                  media_assets, drive_commit_attempts, queue_allocations TO social_app;
                GRANT SELECT, INSERT ON review_events TO social_app;
                REVOKE UPDATE, DELETE, TRUNCATE ON review_events FROM social_app;
                GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO social_app;
              END IF;
            END $$
        """)
    elif op.get_bind().dialect.name == "sqlite":
        op.execute("""CREATE TRIGGER review_events_no_update BEFORE UPDATE ON review_events
                      BEGIN SELECT RAISE(ABORT, 'Review history is append-only'); END""")
        op.execute("""CREATE TRIGGER review_events_no_delete BEFORE DELETE ON review_events
                      BEGIN SELECT RAISE(ABORT, 'Review history is append-only'); END""")

    # ### end Alembic commands ###


def downgrade():
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER review_events_no_changes ON review_events")
        op.execute("DROP TRIGGER review_events_no_truncate ON review_events")
    elif op.get_bind().dialect.name == "sqlite":
        op.execute("DROP TRIGGER review_events_no_update")
        op.execute("DROP TRIGGER review_events_no_delete")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_events_submission_platform_id"))
        batch_op.drop_index(batch_op.f("ix_review_events_submission_id"))

    op.drop_table("review_events")
    with op.batch_alter_table("media_assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_media_assets_submission_platform_id"))
        batch_op.drop_index(batch_op.f("ix_media_assets_submission_id"))

    op.drop_table("media_assets")
    with op.batch_alter_table("drive_commit_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_drive_commit_attempts_submission_platform_id"))
        batch_op.drop_index(batch_op.f("ix_drive_commit_attempts_status"))

    op.drop_table("drive_commit_attempts")
    with op.batch_alter_table("submission_platforms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_submission_platforms_submission_id"))
        batch_op.drop_index(batch_op.f("ix_submission_platforms_status"))

    op.drop_table("submission_platforms")
    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_submissions_target_date"))
        batch_op.drop_index(batch_op.f("ix_submissions_status"))
        batch_op.drop_index(batch_op.f("ix_submissions_creator_id"))
        batch_op.drop_index(batch_op.f("ix_submissions_campaign_id"))

    op.drop_table("submissions")
    op.drop_table("queue_allocations")
    # ### end Alembic commands ###
